# Generated by Django 4.0.4 on 2022-04-30 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudicacion',
            fields=[
                ('cuit', models.CharField(max_length=13)),
                ('apellido_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('adjudicacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('solicitud', models.CharField(blank=True, max_length=45, null=True)),
                ('nro_inscripto', models.CharField(blank=True, max_length=45, null=True)),
                ('dominio', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_adj', models.CharField(blank=True, max_length=45, null=True)),
                ('cod_imp', models.CharField(blank=True, choices=[('2', 'ISIB CM'), ('4', 'ISIB RG'), ('3', 'AP'), ('5', 'PF Caduco'), ('7', 'ABL'), ('8', 'RV'), ('10', 'Abasto'), ('11', 'Mesas y Sillas'), ('12', 'Volquetes'), ('13', 'Kioscos'), ('14', 'Vallas'), ('16', 'Toldos'), ('17', 'Postes'), ('19', 'Uso del Subsuelo'), ('20', 'ISIB AR'), ('21', 'SIRCREB'), ('27', 'Embarcaciones'), ('28', 'Sellos'), ('30', 'Moratoria RV-ABL'), ('31', 'Antenas'), ('40', 'ISIB RS'), ('100', 'Multa DGDyPC')], max_length=15, null=True)),
                ('mandatario', models.CharField(blank=True, max_length=100, null=True)),
                ('juzgado', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=10, null=True)),
                ('oficio', models.CharField(blank=True, max_length=45, null=True)),
                ('secretaria', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2, null=True)),
                ('estado_juicio', models.CharField(blank=True, max_length=45, null=True)),
                ('f_inicio_juic', models.DateField(blank=True, null=True)),
                ('fecha_adj', models.DateField(blank=True, null=True)),
                ('tipo_adm', models.CharField(blank=True, max_length=45, null=True)),
                ('exp_adm', models.CharField(blank=True, max_length=45, null=True)),
                ('año_adm', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_exp', models.CharField(blank=True, max_length=45, null=True)),
                ('año_exped', models.CharField(blank=True, max_length=10, null=True)),
                ('imp_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('puerta', models.CharField(blank=True, max_length=45, null=True)),
                ('piso', models.CharField(blank=True, max_length=45, null=True)),
                ('dpto', models.CharField(blank=True, max_length=45, null=True)),
                ('oficina', models.CharField(blank=True, max_length=45, null=True)),
                ('localidad', models.CharField(blank=True, max_length=45, null=True)),
                ('cod_post', models.CharField(blank=True, max_length=45, null=True)),
                ('const_deuda', models.FileField(blank=True, null=True, upload_to='expedientes_git/constancias/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-f_inicio_juic', 'adjudicacion', '-imp_nominal'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=12, null=True)),
                ('seccion', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('e_mail_agip', models.EmailField(max_length=254)),
                ('foto_user', models.ImageField(blank=True, null=True, upload_to='')),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('seccion',),
            },
        ),
        migrations.CreateModel(
            name='Planes_de_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_actualizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_de_suscripcion', models.DateField()),
                ('modalidad_de_pago', models.CharField(blank=True, choices=[('Contado', 'Contado'), ('Cuotas', 'Cuotas')], default='Contado', max_length=45, null=True)),
                ('cantidad_de_cuotas_plan', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '6'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36')], default='1', max_length=2, null=True)),
                ('honorarios_mandatario', models.DecimalField(blank=True, decimal_places=4, default='22212.81', max_digits=10, null=True)),
                ('honorarios_procuracion', models.DecimalField(blank=True, decimal_places=4, default='7867.58', max_digits=10, null=True)),
                ('fecha_de_pago_honorarios', models.DateField(blank=True, null=True)),
                ('cuotas_de_honorarios', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=2, null=True)),
                ('acredito_comprobante', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2, null=True)),
                ('estado_del_plan', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Nulo', 'Nulo'), ('Cancelado', 'Cancelado'), ('Vigente', 'Vigente')], default='Pendiente', max_length=20, null=True)),
                ('fecha_de_cancelacion', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('archivo_plan', models.FileField(blank=True, null=True, upload_to='planes/planes_de_pago/')),
                ('comprobantes', models.FileField(blank=True, null=True, upload_to='planes/comprobantes/')),
                ('dia_ingreso_plan', models.DateTimeField(auto_now_add=True, null=True)),
                ('adjudicacion', models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_git.seccion')),
            ],
            options={
                'ordering': ('-fecha_de_suscripcion',),
            },
        ),
        migrations.CreateModel(
            name='Embargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_embargo', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Ejecutorio', 'Ejecutorio')], default='preventivo', max_length=45)),
                ('clase_embargo', models.CharField(blank=True, choices=[('SOJ', 'SOJ'), ('BCRA', 'BCRA')], default='SOJ', max_length=45, null=True)),
                ('monto_embargado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(blank=True, choices=[('Trabado', 'Trabado'), ('Lev.solicitado', 'lev.solicitado'), ('Levantado', 'Levantado'), ('Embargo', 'Embargo'), ('S/Oficio', 'S/Oficio')], default='Trabado', max_length=45, null=True)),
                ('fecha_pedido_git', models.DateField(blank=True, null=True, verbose_name='Fecha pedido de Embargo')),
                ('fecha_acreditacion', models.DateField(blank=True, null=True)),
                ('fecha_pedido_levantamiento', models.DateField(blank=True, null=True, verbose_name='Fecha pedido de Levantamiento')),
                ('orden_levantamiento', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=45, null=True)),
                ('fecha_levantamiento_git', models.DateField(blank=True, null=True)),
                ('oficio_embargo', models.FileField(blank=True, null=True, upload_to='embargos/oficios/')),
                ('oficio_lev_embargo', models.FileField(blank=True, null=True, upload_to='embargos/ofic_levantamiento')),
                ('dia_ingreso_embargo', models.DateTimeField(auto_now_add=True)),
                ('adjudicacion', models.OneToOneField(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_git.seccion')),
            ],
            options={
                'ordering': ('-fecha_pedido_git',),
            },
        ),
        migrations.CreateModel(
            name='Comprobantes_de_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobantes', models.FileField(blank=True, null=True, upload_to='planes/comprobantes/')),
                ('dia_ingreso_comprobante', models.DateTimeField(auto_now_add=True, null=True)),
                ('adjudicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cbu_Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, max_length=3, null=True)),
                ('cuit', models.CharField(max_length=15)),
                ('impuesto', models.CharField(blank=True, max_length=3, null=True)),
                ('cbu', models.CharField(max_length=30)),
                ('banco', models.CharField(max_length=200)),
                ('adjudicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion')),
            ],
            options={
                'ordering': ['banco', 'cuit', 'impuesto'],
            },
        ),
        migrations.AddField(
            model_name='adjudicacion',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_git.seccion'),
        ),
    ]
