# Generated by Django 4.0.4 on 2022-11-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_git', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbu_contribuyente',
            name='adjudicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion'),
        ),
        migrations.AlterField(
            model_name='cbu_contribuyente',
            name='seccion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
