# Generated by Django 4.0.4 on 2022-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_git', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_de_pago',
            name='imp_actualizado',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
