# Generated by Django 4.0.4 on 2022-05-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_git', '0002_alter_planes_de_pago_imp_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_de_pago',
            name='adjudicacion',
            field=models.OneToOneField(max_length=45, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion'),
        ),
        migrations.AlterField(
            model_name='planes_de_pago',
            name='fecha_de_suscripcion',
            field=models.DateField(null=True),
        ),
    ]
