# Generated by Django 4.0.4 on 2022-05-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_git', '0003_alter_planes_de_pago_adjudicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_de_pago',
            name='adjudicacion',
            field=models.OneToOneField(default=1, max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_git.adjudicacion'),
            preserve_default=False,
        ),
    ]
