# Generated by Django 4.0.4 on 2022-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_git', '0004_remove_seccion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes_de_pago',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
    ]
