# Generated by Django 4.0.4 on 2023-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_git', '0007_alter_patente_rad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='marca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patente',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
